[build]
  base = "frontend"           # Build runs from the frontend/ directory
  publish = "build"           # Output directory relative to base (frontend/build)
  command = "npm install && npm run build"
  functions = "../functions"  # Functions directory relative to root

[dev]
  command = "npm start"
  port = 3000
  targetPort = 5000
  functionsPort = 8888